# Contiene solo las imágenes de postgres y pg admin
services:
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          PGDATA: /var/lib/postgresql/data
        ports:
          - '5432:5432'
        networks:
          - postgres-network

    pgadmin4:
        image: elestio/pgadmin:latest
        container_name: pgadmin
        restart: always
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: admin
          PGADMIN_LISTEN_PORT: 8080
        ports:
          - "8080:8080"
        volumes:
          - ./servers.json:/pgadmin4/servers.json
        networks:
          - postgres-network

networks:
  postgres-network:
    driver: bridge


