// This file is auto-generated by @hey-api/openapi-ts

export type Client = {
    name: string;
    id?: string;
    isActive?: boolean;
    createdAt?: string;
    modifiedAt?: string;
};

export type ClientPatchDto = {
    name?: string | null;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginResponse = {
    accessToken: string;
    refreshToken: string;
    accessExpiresIn: number;
    refreshExpiresIn: number;
};

export type NotFoundResult = {
    statusCode?: number;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
};

export type TermsAndConditions = {
    name: string;
    content: string;
    id?: string;
    isActive?: boolean;
    createdAt?: string;
    modifiedAt?: string;
};

export type TermsAndConditionsPatchDto = {
    name?: string | null;
    content?: string | null;
};

export type UnauthorizedResult = {
    statusCode?: number;
};

export type PostApiAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: "/api/Auth/login";
};

export type PostApiAuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedResult;
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type GetApiClientData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/Client";
};

export type GetApiClientResponses = {
    /**
     * OK
     */
    200: Array<Client>;
};

export type GetApiClientResponse = GetApiClientResponses[keyof GetApiClientResponses];

export type PostApiClientData = {
    body: Client;
    path?: never;
    query?: never;
    url: "/api/Client";
};

export type PostApiClientErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiClientError = PostApiClientErrors[keyof PostApiClientErrors];

export type PostApiClientResponses = {
    /**
     * Created
     */
    201: Client;
};

export type PostApiClientResponse = PostApiClientResponses[keyof PostApiClientResponses];

export type DeleteApiClientByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/Client/{id}";
};

export type DeleteApiClientByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiClientByIdError = DeleteApiClientByIdErrors[keyof DeleteApiClientByIdErrors];

export type DeleteApiClientByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiClientByIdResponse = DeleteApiClientByIdResponses[keyof DeleteApiClientByIdResponses];

export type GetApiClientByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/Client/{id}";
};

export type GetApiClientByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiClientByIdError = GetApiClientByIdErrors[keyof GetApiClientByIdErrors];

export type GetApiClientByIdResponses = {
    /**
     * OK
     */
    200: Client;
};

export type GetApiClientByIdResponse = GetApiClientByIdResponses[keyof GetApiClientByIdResponses];

export type PatchApiClientByIdData = {
    body: ClientPatchDto;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/Client/{id}";
};

export type PatchApiClientByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PatchApiClientByIdError = PatchApiClientByIdErrors[keyof PatchApiClientByIdErrors];

export type PatchApiClientByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PatchApiClientByIdResponse = PatchApiClientByIdResponses[keyof PatchApiClientByIdResponses];

export type PatchApiClientByIdReactivateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/Client/{id}/reactivate";
};

export type PatchApiClientByIdReactivateErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PatchApiClientByIdReactivateError = PatchApiClientByIdReactivateErrors[keyof PatchApiClientByIdReactivateErrors];

export type PatchApiClientByIdReactivateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PatchApiClientByIdReactivateResponse = PatchApiClientByIdReactivateResponses[keyof PatchApiClientByIdReactivateResponses];

export type GetApiTermsAndConditionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/TermsAndConditions";
};

export type GetApiTermsAndConditionsResponses = {
    /**
     * OK
     */
    200: Array<TermsAndConditions>;
};

export type GetApiTermsAndConditionsResponse = GetApiTermsAndConditionsResponses[keyof GetApiTermsAndConditionsResponses];

export type PostApiTermsAndConditionsData = {
    body: TermsAndConditions;
    path?: never;
    query?: never;
    url: "/api/TermsAndConditions";
};

export type PostApiTermsAndConditionsErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
};

export type PostApiTermsAndConditionsError = PostApiTermsAndConditionsErrors[keyof PostApiTermsAndConditionsErrors];

export type PostApiTermsAndConditionsResponses = {
    /**
     * Created
     */
    201: TermsAndConditions;
};

export type PostApiTermsAndConditionsResponse = PostApiTermsAndConditionsResponses[keyof PostApiTermsAndConditionsResponses];

export type DeleteApiTermsAndConditionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/TermsAndConditions/{id}";
};

export type DeleteApiTermsAndConditionsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type DeleteApiTermsAndConditionsByIdError = DeleteApiTermsAndConditionsByIdErrors[keyof DeleteApiTermsAndConditionsByIdErrors];

export type DeleteApiTermsAndConditionsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteApiTermsAndConditionsByIdResponse = DeleteApiTermsAndConditionsByIdResponses[keyof DeleteApiTermsAndConditionsByIdResponses];

export type GetApiTermsAndConditionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/TermsAndConditions/{id}";
};

export type GetApiTermsAndConditionsByIdErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetApiTermsAndConditionsByIdError = GetApiTermsAndConditionsByIdErrors[keyof GetApiTermsAndConditionsByIdErrors];

export type GetApiTermsAndConditionsByIdResponses = {
    /**
     * OK
     */
    200: TermsAndConditions;
};

export type GetApiTermsAndConditionsByIdResponse = GetApiTermsAndConditionsByIdResponses[keyof GetApiTermsAndConditionsByIdResponses];

export type PatchApiTermsAndConditionsByIdData = {
    body: TermsAndConditionsPatchDto;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/TermsAndConditions/{id}";
};

export type PatchApiTermsAndConditionsByIdErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PatchApiTermsAndConditionsByIdError = PatchApiTermsAndConditionsByIdErrors[keyof PatchApiTermsAndConditionsByIdErrors];

export type PatchApiTermsAndConditionsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PatchApiTermsAndConditionsByIdResponse = PatchApiTermsAndConditionsByIdResponses[keyof PatchApiTermsAndConditionsByIdResponses];

export type PatchApiTermsAndConditionsByIdReactivateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/TermsAndConditions/{id}/reactivate";
};

export type PatchApiTermsAndConditionsByIdReactivateErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type PatchApiTermsAndConditionsByIdReactivateError = PatchApiTermsAndConditionsByIdReactivateErrors[keyof PatchApiTermsAndConditionsByIdReactivateErrors];

export type PatchApiTermsAndConditionsByIdReactivateResponses = {
    /**
     * No Content
     */
    204: void;
};

export type PatchApiTermsAndConditionsByIdReactivateResponse = PatchApiTermsAndConditionsByIdReactivateResponses[keyof PatchApiTermsAndConditionsByIdReactivateResponses];

export type ClientOptions = {
    baseUrl: "http://localhost:5233" | (string & {});
};
