// This file is auto-generated by @hey-api/openapi-ts

export type Client = {
    name: string;
    id?: string;
    isActive?: boolean;
    createdAt?: string;
    modifiedAt?: string;
};

export type ClientPatchDto = {
    name?: string | null;
};

export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginResponse = {
    accessToken: string;
    refreshToken: string;
    accessExpiresIn: number;
    refreshExpiresIn: number;
};

export type TermsAndConditions = {
    name: string;
    content: string;
    id?: string;
    isActive?: boolean;
    createdAt?: string;
    modifiedAt?: string;
};

export type TermsAndConditionsPatchDto = {
    name?: string | null;
    content?: string | null;
};

export type UnauthorizedResult = {
    statusCode?: number;
};

export type PostApiAuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: "/api/Auth/login";
};

export type PostApiAuthLoginErrors = {
    /**
     * Unauthorized
     */
    401: UnauthorizedResult;
};

export type PostApiAuthLoginError = PostApiAuthLoginErrors[keyof PostApiAuthLoginErrors];

export type PostApiAuthLoginResponses = {
    /**
     * OK
     */
    200: LoginResponse;
};

export type PostApiAuthLoginResponse = PostApiAuthLoginResponses[keyof PostApiAuthLoginResponses];

export type GetApiClientData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/Client";
};

export type GetApiClientResponses = {
    /**
     * OK
     */
    200: Array<Client>;
};

export type GetApiClientResponse = GetApiClientResponses[keyof GetApiClientResponses];

export type PostApiClientData = {
    body: Client;
    path?: never;
    query?: never;
    url: "/api/Client";
};

export type PostApiClientResponses = {
    /**
     * OK
     */
    200: Client;
};

export type PostApiClientResponse = PostApiClientResponses[keyof PostApiClientResponses];

export type DeleteApiClientByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/Client/{id}";
};

export type DeleteApiClientByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiClientByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/Client/{id}";
};

export type GetApiClientByIdResponses = {
    /**
     * OK
     */
    200: Client;
};

export type GetApiClientByIdResponse = GetApiClientByIdResponses[keyof GetApiClientByIdResponses];

export type PatchApiClientByIdData = {
    body: ClientPatchDto;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/Client/{id}";
};

export type PatchApiClientByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiClientByIdReactivateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/Client/{id}/reactivate";
};

export type PatchApiClientByIdReactivateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTermsAndConditionsData = {
    body?: never;
    path?: never;
    query?: never;
    url: "/api/TermsAndConditions";
};

export type GetApiTermsAndConditionsResponses = {
    /**
     * OK
     */
    200: Array<TermsAndConditions>;
};

export type GetApiTermsAndConditionsResponse = GetApiTermsAndConditionsResponses[keyof GetApiTermsAndConditionsResponses];

export type PostApiTermsAndConditionsData = {
    body: TermsAndConditions;
    path?: never;
    query?: never;
    url: "/api/TermsAndConditions";
};

export type PostApiTermsAndConditionsResponses = {
    /**
     * OK
     */
    200: TermsAndConditions;
};

export type PostApiTermsAndConditionsResponse = PostApiTermsAndConditionsResponses[keyof PostApiTermsAndConditionsResponses];

export type DeleteApiTermsAndConditionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/TermsAndConditions/{id}";
};

export type DeleteApiTermsAndConditionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetApiTermsAndConditionsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/TermsAndConditions/{id}";
};

export type GetApiTermsAndConditionsByIdResponses = {
    /**
     * OK
     */
    200: TermsAndConditions;
};

export type GetApiTermsAndConditionsByIdResponse = GetApiTermsAndConditionsByIdResponses[keyof GetApiTermsAndConditionsByIdResponses];

export type PatchApiTermsAndConditionsByIdData = {
    body: TermsAndConditionsPatchDto;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/TermsAndConditions/{id}";
};

export type PatchApiTermsAndConditionsByIdResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PatchApiTermsAndConditionsByIdReactivateData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: "/api/TermsAndConditions/{id}/reactivate";
};

export type PatchApiTermsAndConditionsByIdReactivateResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type ClientOptions = {
    baseUrl: "http://localhost:5233" | (string & {});
};
